# Generated by Django 2.1.5 on 2019-01-07 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_archivourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='archivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ArchivoUrl'),
        ),
    ]
